---
# create sudoer - full playbook
- hosts: localhost
  become: true
  become_method: sudo
  become_user: root
  
  tasks:
  - name: check user is sudoer
    user:
      name: "{{ newSudoer }}"
      state: present
      password: $6$l3wt5p33$uPKT/QPD8NpIMuJMcoRwlG1ytN.O2jqJwZFSEnTn1xctjl9lz8yPj/qv1vORLcF0KsJuzLrYFJL0bvfM4HqAT1
      groups: sudo
    become: true
      
 # - name: reset pass
 #   command: sudo passwd "{{ newSudoer }}"

  #- name: Ensure passwordless sudo for '{{ newSudoer }}'
  #  lineinfile:
  #    dest: /etc/sudoers
  #    state: present
  #    regexp: '^%{{ newSudoer }}'
  #    line: '%{{ newSudoer }} ALL=(ALL) NOPASSWD: ALL'
  #    validate: 'visudo -cf %s'
  #  become: yes
  #  become_method: sudo
